export const townList = [
  {
    name: 'Москва',
    id: '524901',
    temp: '',
    description: '',
    icon: '',
  },
  {
    name: 'Санкт-Петербург',
    id: '498817',
    temp: '',
    description: '',
    icon: '',
  },
  {
    name: 'Новосибирск',
    id: '1496747',
    temp: '',
    description: '',
    icon: '',
  },
  {
    name: 'Екатеринбург',
    id: '1486209',
    temp: '',
    description: '',
    icon: '',
  },
  {
    name: 'Нижний Новгород',
    id: '520555',
    temp: '',
    description: '',
    icon: '',
  },
  {
    name: 'Казань',
    id: '551487',
    temp: '',
    description: '',
    icon: '',
  },
  {
    name: 'Сочи',
    id: '491422',
    temp: '',
    description: '',
    icon: '',
  },
];
